# Generated by Django 2.1.5 on 2020-07-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=5)),
                ('pre', models.IntegerField()),
            ],
        ),
    ]
