# Generated by Django 2.1.5 on 2020-07-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='modelo',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
