# Generated by Django 2.1.5 on 2020-07-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0002_auto_20200714_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='prom',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
