# Generated by Django 2.1.5 on 2020-07-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modelo', models.ImageField(upload_to='pics')),
                ('des', models.TextField()),
                ('cant', models.CharField(max_length=100)),
                ('pre', models.IntegerField()),
                ('prom', models.BooleanField()),
            ],
        ),
    ]
