# Generated by Django 2.1.5 on 2020-08-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wear', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wear',
            old_name='des',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='wear',
            old_name='modelo',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='wear',
            old_name='prom',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='wear',
            old_name='pre',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='wear',
            old_name='cant',
            new_name='quant',
        ),
        migrations.AddField(
            model_name='wear',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=100),
            preserve_default=False,
        ),
    ]
