# Generated by Django 2.1.5 on 2020-07-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200727_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='direccion',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sexo',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telefono',
            new_name='phone',
        ),
    ]
