# Generated by Django 2.1.5 on 2020-07-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200727_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(blank=True, default='Urb. ', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=100),
        ),
    ]
