# Generated by Django 2.1.5 on 2020-08-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200801_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=100),
        ),
    ]
