# Generated by Django 2.1.5 on 2020-07-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200724_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
